// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5ciO4nl9QvGMCFAydmInCF3uFx6flcg',
    appId: '1:875116012151:web:c56d617ebb4a3921521c72',
    messagingSenderId: '875116012151',
    projectId: 'vehicle-damage-app',
    authDomain: 'vehicle-damage-app.firebaseapp.com',
    storageBucket: 'vehicle-damage-app.firebasestorage.app',
    measurementId: 'G-PJ1TDCSVY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0LfXbmB0y9S6l5AYvBL82Buyp--w4ag',
    appId: '1:875116012151:android:a864253f4743b9f8521c72',
    messagingSenderId: '875116012151',
    projectId: 'vehicle-damage-app',
    storageBucket: 'vehicle-damage-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD5ciO4nl9QvGMCFAydmInCF3uFx6flcg',
    appId: '1:875116012151:ios:vehicle-damage-app-ios',
    messagingSenderId: '875116012151',
    projectId: 'vehicle-damage-app',
    storageBucket: 'vehicle-damage-app.firebasestorage.app',
    iosBundleId: 'com.example.vehicleDamageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD5ciO4nl9QvGMCFAydmInCF3uFx6flcg',
    appId: '1:875116012151:macos:vehicle-damage-app-macos',
    messagingSenderId: '875116012151',
    projectId: 'vehicle-damage-app',
    storageBucket: 'vehicle-damage-app.firebasestorage.app',
    iosBundleId: 'com.example.vehicleDamageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD5ciO4nl9QvGMCFAydmInCF3uFx6flcg',
    appId: '1:875116012151:windows:vehicle-damage-app-windows',
    messagingSenderId: '875116012151',
    projectId: 'vehicle-damage-app',
    storageBucket: 'vehicle-damage-app.firebasestorage.app',
  );
}
