// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project configuration
  // You can get these values from your Firebase Console
  // Go to Project Settings > General > Your apps
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-example-web-api-key',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'vehicle-damage-app-example',
    authDomain: 'vehicle-damage-app-example.firebaseapp.com',
    storageBucket: 'vehicle-damage-app-example.appspot.com',
    measurementId: 'G-EXAMPLE123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-example-android-api-key',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'vehicle-damage-app-example',
    storageBucket: 'vehicle-damage-app-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-example-ios-api-key',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'vehicle-damage-app-example',
    storageBucket: 'vehicle-damage-app-example.appspot.com',
    iosBundleId: 'com.example.vehicleDamageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-example-macos-api-key',
    appId: '1:123456789012:macos:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'vehicle-damage-app-example',
    storageBucket: 'vehicle-damage-app-example.appspot.com',
    iosBundleId: 'com.example.vehicleDamageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-example-windows-api-key',
    appId: '1:123456789012:windows:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'vehicle-damage-app-example',
    storageBucket: 'vehicle-damage-app-example.appspot.com',
  );
}
